{% set name = "PartSeg" %}
{% set version = "0.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: a8047eaf5e4cf3a065a078ad2d62739d13f417274e6e0e76603e51f2b9b1936e

build:
  noarch: python
  entry_points:
    - PartSeg = PartSeg.launcher_main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm >=8
    - setuptools
  run:
    - appdirs >=1.4.4
    - czifile >=2019.5.22
    - defusedxml >=0.6.0
    - fonticon-fontawesome6 >=6.4.0
    - h5py >=3.3.0
    - imagecodecs >=2020.5.30
    - imageio >=2.20.0
    - ipykernel >=5.2.0
    - ipython >=7.7.0
    - local-migrator >=0.1.7
    - magicgui >=0.7.0
    - mahotas >=1.4.12
    - napari >=0.5.0
    - nme >=0.1.7
    - numpy >=1.22.2
    - oiffile >=2020.1.18
    - openpyxl >=3.0.7
    - packaging >=22.0
    - pandas >=1.3.0
    - partsegcore-compiled-backend >=0.13.11
    - partsegdata ==0.10.0
    - psygnal >=0.3.1
    - pydantic >=1.9.1
    - pygments >=2.12.0
    - python >={{ python_min }}
    - qtawesome >=1.2.1
    - qtconsole >=4.7.7
    - qtpy >=1.10.0
    - requests >=2.25.0
    - scipy >=1.5.4
    - sentry-sdk >=2.4.0
    - simpleitk >=2.1.0
    - six >=1.11.0
    - superqt >=0.6.71
    - sympy >=1.10
    - tifffile >=2022.4.8
    - traceback-with-variables >=2.0.4
    - vispy >=0.14.1
    - xlrd >=1.1.0
    - xlsxwriter >=2.0.0

test:
  imports:
    - PartSeg
    - PartSegCore
    - PartSegImage
  commands:
    - pip list
    - pip check
    - PartSeg --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://4dnucleome.cent.uw.edu.pl/PartSeg/
  summary: PartSeg is python GUI and set of napari plugins for bio imaging analysis especially nucleus analysis,
  license: BSD-3-Clause
  license_file: License.txt
  dev_url: https://github.com/4DNucleome/PartSeg

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Czaki
