{% set name = "PartSeg" %}
{% set version = "0.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PartSeg-{{ version }}.tar.gz
  sha256: 505b53bc41e7f67b7c2fd5b5840c601f6a9ce6633b2965540e9af8f299926bec

build:
  skip: true  # [py<37]
  entry_points:
    - PartSeg = PartSeg.launcher_main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python
    - setuptools-scm >=3.4
    - setuptools-scm
  run:
    - appdirs >=1.4.4
    - czifile >=2019.5.22
    - defusedxml >=0.6.0
    - h5py >=2.8.0
    - imagecodecs >=2020.5.30
    - imageio >=2.5.0
    - ipykernel >=5.2.0
    - ipython >=7.7.0
    - magicgui >=0.3.3
    - mahotas >=1.4.9
    - napari >=0.4.8
    - nme >=0.1.6
    - numpy >=1.18.0
    - oiffile >=2019.1.1  # [py>=38]
    - oiffile <=2021.6.6  # [py<38]
    - openpyxl >=2.4.9
    - packaging >=20.0
    - pandas >=0.24.0
    - partsegcore-compiled-backend >=0.13.11
    - partsegdata ==0.10.0
    - psygnal >=0.2.0
    - pydantic >=1.6.1
    - python
    - qtawesome >=1.0.3, !=1.2.0
    - qtpy >=1.7.0
    - requests >=2.18.0
    - scipy >=1.2.0
    - sentry-sdk >=0.14.3
    - simpleitk >=1.1.0
    - six >=1.11.0
    - superqt >=0.2.4
    - sympy >=1.1.1
    - tifffile >=2020.9.30
    - traceback-with-variables >=2.0.4
    - typing-extensions >=3.7.4.3  # [py<38]
    - vispy >=0.6.4
    - xlrd >=1.1.0
    - xlsxwriter

test:
  imports:
    - PartSeg
    - PartSegCore
    - PartSegImage
  commands:
    - pip list
    - pip check
    - PartSeg --help
  requires:
    - pip

about:
  home: https://4dnucleome.cent.uw.edu.pl/PartSeg/
  summary: PartSeg is python GUI and set of napari plugins for bio imaging analysis especially nucleus analysis,
  license: BSD-3-Clause
  license_file: License.txt
  dev_url: https://github.com/4DNucleome/PartSeg

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Czaki
