{% set name = "PartSeg" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PartSeg-{{ version }}.tar.gz
  sha256: da7f9e2e3f6b9131d6a1019c552cdd81afe88aafeed3db6614f2e1394143bb8c

build:
  skip: true  # [py<37]
  entry_points:
    - PartSeg = PartSeg.launcher_main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools-scm >=3.4
    - setuptools-scm
  run:
    - appdirs >=1.4.4
    - czifile >=2019.5.22
    - defusedxml >=0.6.0
    - fonticon-fontawesome6 >=6.4.0
    - h5py >=3.3.0
    - imagecodecs >=2020.5.30
    - imageio >=2.5.0
    - ipykernel >=5.2.0
    - ipython >=7.7.0
    - local-migrator >=0.1.7
    - magicgui >=0.4.0
    - mahotas >=1.4.9
    - napari >=0.4.14
    - nme >=0.1.7
    - numpy >=1.18.5
    - oiffile >=2020.1.18  # [py>=38]
    - oiffile <=2021.6.6  # [py<38]
    - openpyxl >=2.5.7
    - packaging >=20.0
    - pandas >=1.1.0
    - partsegcore-compiled-backend >=0.13.11
    - partsegdata ==0.10.0
    - psygnal >=0.3.1
    - pydantic >=1.8.1
    - pygments >=2.4.0
    - python
    - qtawesome >=1.0.3, !=1.2.0
    - qtconsole >=4.7.7
    - qtpy >=1.7.0
    - requests >=2.18.0
    - scipy >=1.4.1
    - sentry-sdk >=0.14.3
    - simpleitk >=2.0.0
    - six >=1.11.0
    - superqt >=0.3.0
    - sympy >=1.1.1
    - tifffile >=2020.9.30
    - traceback-with-variables >=2.0.4
    - typing-extensions >=3.7.4.3  # [py<38]
    - vispy >=0.9.4
    - xlrd >=1.1.0
    - xlsxwriter >=2.0.0

test:
  imports:
    - PartSeg
    - PartSegCore
    - PartSegImage
  commands:
    - pip list
    - pip check
    - PartSeg --help
  requires:
    - pip

about:
  home: https://4dnucleome.cent.uw.edu.pl/PartSeg/
  summary: PartSeg is python GUI and set of napari plugins for bio imaging analysis especially nucleus analysis,
  license: BSD-3-Clause
  license_file: License.txt
  dev_url: https://github.com/4DNucleome/PartSeg

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Czaki
